### PR TITLE
Using the minikube variables to find the IP.

### PR DESCRIPTION
**Pull request by JacobFrericks**
Instead of saying "use <minikube_ip>:3200", use the minikube variable so the user can just copy/paste into the commandline.

### CODE REVIEW

**Review by rshriram — APPROVED** [review]
Can you add the same for bookinfo as well?

**Comment by JacobFrericks** [comment]
@rshriram the difference between the helloworld example and the bookinfo example is that in helloworld, the user is asked to use curl, where $(minikube ip) variable can be used. In bookinfo, the user is asked to use the browser, so this won't work. 

Do you still think it would be valuable to add into bookinfo?

**Comment by ijsnellf** [comment]
Maybe just note that they can use `minikube ip` to find the appropriate IP address?

**Comment by JacobFrericks** [comment]
Closing this pull request as it will be superseded by another (coming shortly)

**Pull request closed without merging**
